name: Publish Pre Release

on:
  push:
    tags:
      - v*-alpha.*
      - v*-beta.*
      - v*-rc.*

jobs:
  test:
    uses: dicebear/dicebear/.github/workflows/test.yml@9.x
  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build -- --ignore "@dicebear/@(website|editor)"

      - run:
          ./node_modules/.bin/lerna publish from-package --dist-tag next
          --ignore-scripts --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
